CREATE VIEW V_VOL_SEARCH
AS
SELECT A.*,O_ONAME,SUB_NAME,CLASS_NAME||' '||DCLASS_NAME CN,REGEXP_SUBSTR(O_ADDR, '[^ ]+', 1, 2)||' '||REGEXP_SUBSTR(O_ADDR, '[^ ]+', 1, 3) ADDR,0 COUNT   
FROM VT_RECRUIT A, SUBJECT D, ORGAN E, CLASS F, DCLASS G
WHERE A.VT_O_NO = E.O_NO
AND A.VT_CLASS = G.DCLASS_NO
AND F.CLASS_NO = G.CLASS_NO
AND A.VT_SUBJECT = D.SUB_NO;

SELECT * F