 CREATE OR REPLACE FORCE VIEW "SCOTT"."V_VOL_SEARCH" ("VT_NO", "VT_NAME", "VT_O_NO", "VT_R_START_DATE", "VT_R_END_DATE", "VT_R_YN", "VT_A_START_DATE", "VT_A_END_DATE", "VT_CLASS", "VT_DCLASS", "VT_TOT", "VT_SUBJECT", "VT_DESC", "O_ONAME", "SUB_NAME", "CN", "ADDR", "COUNT") AS 
  SELECT A."VT_NO",A."VT_NAME",A."VT_O_NO",A."VT_R_START_DATE",A."VT_R_END_DATE",A."VT_R_YN",A."VT_A_START_DATE",A."VT_A_END_DATE",A."VT_CLASS",A."VT_DCLASS",A."VT_TOT",A."VT_SUBJECT",A."VT_DESC",O_ONAME,SUB_NAME,CLASS_NAME||' '||DCLASS_NAME CN,REGEXP_SUBSTR(O_ADDR, '[^ ]+', 1, 2)||' '||REGEXP_SUBSTR(O_ADDR, '[^ ]+', 1, 3) ADDR,NVL(COUNT,0) COUNT   
FROM VT_RECRUIT A, SUBJECT D, ORGAN E, CLASS F, DCLASS G, (SELECT VT_NO,COUNT(*) COUNT FROM VT_RQN GROUP BY VT_NO) H
WHERE A.VT_O_NO = E.O_NO
AND A.VT_CLASS = F.CLASS_NO
AND A.VT_DCLASS = G.DCLASS_NO
AND F.CLASS_NO = G.CLASS_NO
AND A.VT_SUBJECT = D.SUB_NO
AND A.VT_NO = H.VT_NO;

create or replace view v_vol_search
as
SELECT A."VT_NO",A."VT_NAME",A."VT_O_NO",A."VT_R_START_DATE",A."VT_R_END_DATE",A."VT_R_YN",A."VT_A_START_DATE",A."VT_A_END_DATE",A."VT_CLASS",A."VT_DCLASS",A."VT_TOT",A."VT_SUBJECT",A."VT_DESC",O_ONAME,SUB_NAME,CLASS_NAME||' '||DCLASS_NAME CN,REGEXP_SUBSTR(O_ADDR, '[^ ]+', 1, 2)||' '||REGEXP_SUBSTR(O_ADDR, '[^ ]+', 1, 3) ADDR, NVL(COUNT,0) COUNT   
FROM VT_RECRUIT A, SUBJECT D, ORGAN E, CLASS F, DCLASS G, (SELECT VT_NO,COUNT(*) COUNT FROM VT_RQN GROUP BY VT_NO) H
WHERE A.VT_O_NO = E.O_NO
AND A.VT_CLASS = F.CLASS_NO
AND A.VT_DCLASS = G.DCLASS_NO
AND F.CLASS_NO = G.CLASS_NO
AND A.VT_SUBJECT = D.SUB_NO
AND A.VT_NO = H.VT_NO;