DROP TABLE VT_RECRUIT;

CREATE TABLE VT_RECRUIT(
  VT_NO	NUMBER PRIMARY KEY,
  VT_NAMNE	VARCHAR2(100) NOT NULL,
  VT_O_NO	NUMBER NOT NULL,
  VT_R_START_DATE	VARCHAR2(8) NOT NULL,
  VT_R_END_DATE	VARCHAR2(8) NOT NULL,
  VT_A_START_DATE	VARCHAR2(8) NOT NULL,
  VT_A_END_DATE	VARCHAR2(8) NOT NULL,
  VT_CLASS	NUMBER NOT NULL,
  VT_TOT	NUMBER NOT NULL,
  VT_SUBJECT	NUMBER NOT NULL,
  VT_DESC	VARCHAR2(4000) NOT NULL
);

SELECT * FROM VT_RECRUIT;

DROP TABLE VT_VOL;

CREATE TABLE VT_VOL(
  VT_VOL_NO NUMBER PRIMARY KEY,
  VT_M_NO NUMBER NOT NULL,
  VT_NO NUMBER NOT NULL,
  VT_REG_DATE DATE DEFAULT SYSDATE,
  VT_TIME NUMBER DEFAULT 0
);

SELECT * FROM VT_VOL;

DROP TABLE VT_RQN;

CREATE TABLE VT_RQN(
  VT_RQN_NO	NUMBER PRIMARY KEY,
  VT_NO	NUMBER NOT NULL,
  VT_M_NO	NUMBER NOT NULL,
  VT_REG_DATE	DATE DEFAULT SYSDATE,
  VT_SEL_YN	CHAR(1) DEFAULT 'N'
);

SELECT * FROM VT_RQN;

DROP TABLE SIDO;

CREAT TABLE SIDO(
  SIDO_NO NUMBER PRIMARY KEY,
  SIDO_NAME VARCHAR2(20)
);

SELECT * FROM SIDO;

DROP TABLE GUGUN;

CREATE TABLE GUGUN(
  GUGUN_NO NUMBER PRIMARY KEY,
  SIDO_NO NUMBER NOT NULL,
  GUGUN_NAME VARCHAR2(50) NOT NULL
);

SELECT * FROM GUGUN;

CREATE TABLE SUBJECT(
  SUB_NO	NUMBER PRIMARY KEY,
  SUB_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE CLASS(
  CLASS_NO NUMBER PRIMARY KEY,
  CLASS_NAME VARCHAR2(50) NOT NULL
);

CREATE TABLE DCLASS(
  DCLASS_NO NUMBER PRIMARY KEY,
  CLASS_NO NUMBER NOT NULL,
  DCLASS_NAME VARCHAR2(50) NOT NULL
);

SELECT VT_NO,regexp_substr(O_ADDR, '[^ ]+', 1, 2)||' '||regexp_substr(O_ADDR, '[^ ]+', 1, 3) addr,VT_SUBJECT, VT_TOTAL, VT_CYCLE, VT_START_DATE, VT_END_DATE FROM VT_REQUEST R, ORGAN O WHERE R.VT_REG_O_NO = O.O_NO ORDER BY VT_NO DESC;
SELECT R.*,nvl(V.reqcount,0) FROM VT_REQUEST R, (SELECT VT_REQ_NO,COUNT(*) reqcount FROM VT_VOLREQ GROUP BY VT_REQ_NO) V WHERE R.VT_NO = V.VT_REQ_NO(+);